"use client";

import { SignalTable } from "@/components/signals/SignalTable";
import { useSignals } from "@/hooks/use-signals";

export default function SignalsPage() {
  const { signals, loading, error, refresh } = useSignals();

  return (
    <main className="page">
      <h1>Signals</h1>
      <p className="muted">Generated by trading-engine SMC V1 (sample data by default).</p>
      <div className="panel">
        <button type="button" onClick={() => void refresh()} disabled={loading}>
          {loading ? "Loading…" : "Refresh"}
        </button>
        {error ? <p className="error">{error}</p> : null}
        {!loading && !error ? <SignalTable signals={signals} /> : null}
      </div>
    </main>
  );
}
